### ISSUE TITLE
 undefined method `resume' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by rgaufman** [jsaak/ruby-mqtt3#3]
Hi there, this file looks fantastic but I have an issue, when I try to run the example, I just get this:

```
Romans-iMac.local ➜  ~  git clone https://github.com/jsaak/ruby-mqtt3.git
Cloning into 'ruby-mqtt3'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 66 (delta 33), reused 54 (delta 21), pack-reused 0
Receiving objects: 100% (66/66), 19.32 KiB | 3.22 MiB/s, done.
Resolving deltas: 100% (33/33), done.
Romans-iMac.local ➜  ~  cd ruby-mqtt3
Romans-iMac.local ➜  ruby-mqtt3 git:(master) ruby example.rb
/usr/local/lib/ruby/gems/3.1.0/gems/async-2.0.2/lib/async/scheduler.rb:106:in `resume': undefined method `resume' for nil:NilClass (NoMethodError)

				@selector.resume(fiber, *arguments)
				         ^^^^^^^
	from /usr/local/lib/ruby/gems/3.1.0/gems/async-2.0.2/lib/async/task.rb:273:in `schedule'
	from /usr/local/lib/ruby/gems/3.1.0/gems/async-2.0.2/lib/async/task.rb:120:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/async-2.0.2/lib/async/scheduler.rb:273:in `async'
	from /usr/local/lib/ruby/gems/3.1.0/gems/async-2.0.2/lib/async/scheduler.rb:280:in `fiber'
	from /Users/hackeron/ruby-mqtt3/ruby-mqtt3.rb:539:in `schedule'
	from /Users/hackeron/ruby-mqtt3/ruby-mqtt3.rb:539:in `run'
	from example.rb:75:in `<main>'
```

I am running on ruby 3.1

Any ideas?

UPDATE: It works with backend = 'libev' but would be good to get it working with "async"

**Comment by jsaak** [comment]
It is some async issue, you can try async (1.29.1), that is what i have
Also there should be a proper async gem which implements the ruby scheduler interface, but I can not find it.

**Comment by rgaufman** [comment]
Any chance adding support for the newer sync versions? :) — also, yes, would be great to leverage Ruby 3.1 improvements!

**Comment by jsaak** [comment]
libev is following the specification, async v2 too (i hope), so if you want to use async2, you need to call it like libev:

```
scheduler = Async::Scheduler.new
```

```
scheduler.run
```

**Comment by rgaufman** [comment]
Yes, that seems to work! - but now I have a new issue, created a new task as it's unrelated.
